Generate layers interactive 

Zone by Layer

    base elevation
      elevation from raster file
        ../Mesh/elevation.asc
    offset base
     -30
    end base elevation


new layer
    layer name
      Layer0
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer0.asc
end

new layer
    layer name
      Layer1
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer1.asc
end

new layer
    layer name
      Layer2
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer2.asc
end

new layer
    layer name
      Layer3
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer3.asc
end

new layer
    layer name
      Layer4
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer4.asc
end

new layer
    layer name
      Layer5
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer5.asc
end

new layer
    layer name
      Layer6
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer6.asc
end

new layer
    layer name
      Layer7
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer7.asc
end

new layer
    layer name
      Layer8
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer8.asc
end

new layer
    layer name
      Layer9
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer9.asc
end

new layer
    layer name
      Layer10
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer10.asc
end

new layer
    layer name
      Layer11
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer11.asc
end

new layer
    layer name
      Layer12
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer12.asc
end

new layer
    layer name
      Layer13
    Minimum layer thickness
      0.0001
    elevation from raster file
      ../Mesh/Layers/Layer13.asc
end

new layer
    layer name
      Layer14
    Minimum layer thickness
      0.0001
      elevation from raster file
        ../Mesh/elevation.asc
      end
end
end grid generation
