

Make observation point
obs_1
55 50 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_2
255 50 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_3
95 150 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_4
35 200 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_5
255 250 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_6
55 300 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_7
235 350 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments


Make observation point
obs_8
55 450 85

clear chosen zones
clear chosen nodes
clear chosen elements
clear chosen faces
clear chosen segments
